version: '3.8'

services:
  uniscrape:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniscrape_app
    volumes:
      - ./uniscrape:/uniscrape
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 8G
